export enum SocialTitleEnum {
  TELEGRAM = 'telegram',
  INSTAGRAM = 'instagram',
  FACEBOOK = 'facebook',
  TWITTER = 'twitter',
  SNAPCHAT = 'snapchat',
  YOUTUBE = 'youtube',
  TIKTOK = 'tiktok',
  GITHUB = 'github',
  GITLAB = 'gitlab',
  BITBUCKET = 'bitbucket',
  TWITCH = 'twitch',
  APARAT = 'aparat',
  REDDIT = 'reddit',
  WHATSAPP = 'whatsapp',
  LINKEDIN = 'linkedin',
  SOUNDCLOUD = 'soundcloud',
  PINTEREST = 'pinterest',
  SPOTIFY = 'spotify',
  APPLEMUSIC = 'applemusic',
  GOOGLEPLAY = 'googleplay',
  STEAM = 'steam',
  DRIBBBLE = 'dribbble',
}
